services:
  db:
    image: postgres:16
    environment:
      POSTGRES_DB: monocrypt
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password123
    ports:
      - "5432:5432"
  
  redis:
    image: redis:7.0.15
    restart: unless-stopped
    ports:
      - "6379:6379"

  bot:
    build: .
    restart: unless-stopped
    environment:
      - BOT_API=${BOT_API}
      - REDIS_URL=redis://redis:6379/0
      - DATABASE_URL=postgresql://user:password123@db:5432/monocrypt
    depends_on:
      - db
      - redis
